In [1]:
# Import the dependency.
import pandas as pd

In [4]:
#  Read in the dataset. 
crowdFunding_df = pd.read_excel("../Starter_Files/Resources/crowdfunding.xlsx")
crowdFunding_df

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks

In [6]:
# Splitting the "category & sub-category" column into 2 separate columns
crowdFunding_df[['category', 'sub-category']] = crowdFunding_df['category & sub-category'].str.split('/', expand=True)

# Dropping the combined column and just keeping the separated columns
crowdFunding_df = crowdFunding_df.drop(columns=['category & sub-category'])
crowdFunding_df

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category,sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater,plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food,food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater,plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater,plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music,indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food,food trucks

In [7]:
#grabbing unique categories
unique_categories = crowdFunding_df['category'].unique()

#creating category Data Frame
category_df = pd.DataFrame({
    'category_id': [f'cat{i+1}' for i in range(len(unique_categories))],
    'category': unique_categories
})
category_df

  category_id      category
0        cat1          food
1        cat2         music
2        cat3    technology
3        cat4       theater
4        cat5  film & video
5        cat6    publishing
6        cat7         games
7        cat8   photography
8        cat9    journalism

In [11]:
#grabbing unique sub-categories
unique_subCategories = crowdFunding_df['sub-category'].unique()

#creating sub-category Data Frame
subCategory_df = pd.DataFrame({
    'subcategory_id': [f'cat{i+1}' for i in range(len(unique_subCategories))],
    'subcategory': unique_subCategories
})
subCategory_df

   subcategory_id        subcategory
0            cat1        food trucks
1            cat2               rock
2            cat3                web
3            cat4              plays
4            cat5        documentary
5            cat6     electric music
6            cat7              drama
7            cat8         indie rock
8            cat9          wearables
9           cat10         nonfiction
10          cat11          animation
11          cat12        video games
12          cat13             shorts
13          cat14            fiction
14          cat15  photography books
15          cat16   radio & podcasts
16          cat17              metal
17          cat18               jazz
18          cat19       translations
19          cat20         television
20          cat21       mobile games
21          cat22        world music
22          cat23    science fiction
23          cat24              audio